### ISSUE TITLE
Картинка

### ISSUE THREAD

**Issue by dmitry-spi** [dimonzp/pizza-order#1]
https://github.com/dimonzp/pizza-order/blob/e290e16f545b9c15be6f61fa70fbde31b5012bd3/react-backend/client/src/component/redux/drink-reducer.js#L2

Изображения, которые юзаются должны быть либо частью данных и нахожится внутри объекта здесь:
https://github.com/dimonzp/pizza-order/blob/e290e16f545b9c15be6f61fa70fbde31b5012bd3/react-backend/client/src/component/redux/drink-reducer.js#L7

либо вынести вообще это куда-то в стили, шаблоны.

**Comment by dimonzp** [comment]
Поместил ссылку в объект
