### ISSUE TITLE
ESlint

### ISSUE THREAD

**Issue by dmitry-spi** [dimonzp/pizza-order#2]
https://github.com/dimonzp/pizza-order/blob/e290e16f545b9c15be6f61fa70fbde31b5012bd3/react-backend/client/src/component/redux/drink-reducer.js#L23

Стоит сразу подключить eslint и использовать готовый шаблон какой-то. Типа airbnb. Тогда код будет сразу красивый.

**Comment by dimonzp** [comment]
Подключил, настроил. Отдельно для клиента (eslint-config-airbnb) и отдельно для сервера (eslint-config-airbnb-base)
